version: '2.1'
orbs:
  slack: circleci/slack@4.1
executors:
  default:
    docker:
      - image: 'hashicorp/terraform:latest'
    resource_class: medium
commands:
  terraform:
    parameters:
      command:
        default: ""
        type: string
    steps:
      - run:
          name: Terraform <<parameters.command>>
          command: terraform <<parameters.command>>


jobs:
  gitleaks:
    docker:
      - image: 'zricethezav/gitleaks'
    steps:
      - checkout
      - run:
          name: 'Credentials scanning'
          command: gitleaks detect -v -f .
      - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
  validation:
    executor: default
    steps:
      - checkout
      - terraform:
          command: init
      - terraform:
          command: validate
  terraform_plan:
    executor: default
    steps:
      - checkout
      - terraform:
          command: init
      - terraform:
          command: plan
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  terraform_apply:
    executor: default
    steps:
      - attach_workspace:
          at: ~/project
      - terraform:
          command: apply


workflows:
  infra-creation:
    jobs:
      - gitleaks:
          context: slack
      - validation:
          requires:
            - gitleaks
      - terraform_plan:
          context:
            - slack
            - AWS-CREDENTIALS
          requires:
            - gitleaks
            - validation
      - terraform_apply:
          context:
            - slack
            - AWS-CREDENTIALS
          requires:
            - terraform_plan
          filters:
            branches:
              only: 
              - Dev
              - main

