version: 2.1
jobs:
  terraform-validate:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: "Terraform init"
          command: "terraform init"
      - run:
          name: "Terraform validate"
          command: "terraform validate"
  terraform-plan:
    docker: 
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: "Terraform init"
          command: "terraform init"
      - run:
          name: "Terraform plan"
          command: "terraform plan"
  terraform-apply:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: "Terraform init"
          command: "terraform init"
      - run:
          name: "Terraform apply"
          command: "terraform apply"

workflows:
  infra-creation:
    jobs:
      - terraform-validate:
          context: terraform
      - terraform-plan:
          context: terraform
          requires:
            - terraform-validate
      - terraform-apply:
          context: terraform
          requires:
            - terraform-plan
          filters:
            branches:
              only: main


