version: 2.1
orbs:
  terraform: circleci/terraform@3.2.0
workflows:
  deploy_infrastructure:
    jobs:
    - terraform/plan:
        checkout: true
        context: terraform
        persist-workspace: true
    - terraform/apply:
        attach-workspace: true
        context: terraform
        filters:
          branches:
            only: main
        requires:
        - terraform/plan